ForkyCode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ForkyCodeApp.urls')),
]

ForkyCodeApp/urls.py
from django.contrib import admin
from django.conf.urls import url
from ForkyCodeApp.Views import home, challenge, session, leaderbords, forum, landing, profile

app_name = 'ForkyCodeApp'
urlpatterns = [
    url(r'^home$', home.Home.as_view(), name="Home"),
    url(r'^login$', session.Login.as_view(), name="Login"),
    url(r'^logout$', session.logoutSession, name="Logout"),
    url(r'^signup$', session.Signup.as_view(), name="Signup"),
    url(r'^challenge$', challenge.Challenge.as_view(), name="Challenge"),
    url(r'^get_leader_data$', leaderbords.getLeaderData, name="GetLeaderData"),
    url(r'^get_forum_data$', forum.getForumData, name="GetForumData"),
    url(r'^createEntry$', forum.CreateEntry.as_view(), name="CreateEntry"),
    url(r'^loadChallenges$', challenge.loadChallenges, name="LoadChallenges"),
    url(r'^get_forum_entry_data$', forum.getForumEntryData, name="GetForumEntryData"),
    url(r'^createComment$', forum.postComment, name="CreateComment"),
    url(r'^$', landing.Landing.as_view(), name="Landing"),
    url(r'^get_profile_data$', profile.loadProfile , name="GetProfileData"),
    url(r'^.*$', home.Default.as_view(), name="Default"),
]

ForkyCodeApp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Forker(models.Model):
    email = models.CharField(max_length=100, db_column='user', primary_key=True)
    password = models.CharField(max_length=100)
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    points = models.IntegerField(default=0)
    favorite_language = models.CharField(max_length=15, default='No language')

    def __str__(self):
        return self.email


class DataType(models.Model):
    TYPES = (
        ('null', 'null'),
        ('void', 'void'),
        ('integer', 'integer'),
        ('string', 'string'),
        ('float', 'float'),
        ('char', 'char'),
        ('array', 'array'),
        ('dict', 'dict'),
    )
    type = models.CharField(max_length=20, choices=TYPES, default='null')

    def __str__(self):
        return self.type


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Challenge(models.Model):
    LEVELS = (
        ('Hard', 'Hard'),
        ('Medium', 'Medium'),
        ('Easy', 'Easy'),
        ('None', 'None')
    )
    description = models.CharField(max_length=10000)
    level = models.CharField(max_length=10, choices=LEVELS, default='None')
    function_name = models.CharField(max_length=20)
    points = models.IntegerField(validators=[MaxValueValidator(500), MinValueValidator(1)], default=1)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return self.function_name + "_id=" + str(self.id)


class TestCase(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    is_real = models.BooleanField(default=False)
    correct_result = models.CharField(max_length=10000)
    correct_type = models.ForeignKey(DataType, on_delete=models.PROTECT)

    def __str__(self):
        return self.challenge.function_name + "_case_id=" + str(self.id)


class ParameterConfig(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    parameter_name = models.CharField(max_length=20, null=False)
    parameter_type = models.ForeignKey(DataType, on_delete=models.PROTECT)
    order = models.IntegerField(default=-1)

    def __str__(self):
        return self.challenge.function_name + "_id=" + str(self.challenge.id) + " param: " + self.parameter_name


class Parameter(models.Model):
    test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE)
    parameter_config = models.ForeignKey(ParameterConfig, on_delete=models.CASCADE)
    parameter_value = models.CharField(max_length=100)

    def __str__(self):
        return self.parameter_config.challenge.function_name + "_test_id=" + str(self.test_case.id) + " param: " + self.parameter_config.parameter_name + " val: " + self.parameter_value


class ForumEntry(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    author = models.ForeignKey(Forker, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True,null=False)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class ForumComment(models.Model):
    description = models.CharField(max_length=1000)
    entry = models.ForeignKey(ForumEntry, on_delete=models.CASCADE)
    author = models.ForeignKey(Forker, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True, null=False)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    def __str__(self):
        return self.entry.title + '_' + str(self.id)


class CompletedChallenges(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    forker = models.ForeignKey(Forker, on_delete=models.CASCADE)

    def __str__(self):
        return self.challenge.function_name + "_" + self.forker.email

ForkyCodeApp/views.py
# Create your views here.

ForkyCodeApp/templates/Challenges/challenges.html
{% load staticfiles %}
<form action="{% url 'ForkyCodeApp:LoadChallenges' %}" method="get" id="load_challenges"></form>
<div class="container">
    <div class="row">
        <div class="col s12 s12">
            <ul class="collapsible" id="challenges_collection">

            </ul>
        </div>
    </div>
</div>

ForkyCodeApp/templates/Editor/editor.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Challenge</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.ico' %}"/>
    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/md-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/editor.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <!-- CodeMirror css and js -->
    <script src="{% static 'codemirror/libr/codemirror.js' %}"></script>
    <link rel="stylesheet" href="{% static 'codemirror/libr/codemirror.css'%}">
    <script src="{% static 'codemirror/mode/python/python.js' %}"></script>
    <link rel="stylesheet" href="{% static 'codemirror/theme/paraiso-dark.css' %}">

    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/challenge.js' %}"></script>

</head>
<body onload="checkIfMobileUser()">
    <div id="overlay">
        <div class="overlay-container">
            <p>Sorry, this feature isn't available in your device</p>
            <a href="/home">Return to Home</a>
            <br><br>
            <img src="{% static 'media/yoda-pixel.png' %}" style="margin: 0 auto; width: 100%;">
        </div>
    </div>
    <form action="{% url 'ForkyCodeApp:Logout' %}" id="logout" hidden></form>
    {% include 'Navbar/editor-navbar.html' %}
    <div class="container-custom">
        <div id="desc-content" class="col s4">
            <!-- Tab links -->
            <div class="tab">
                <button id="desc-btn" class="tablinks" onclick="openTab(event, 'desc')">Description</button>
                <button id="tests-btn" class="tablinks" onclick="openTab(event, 'tests')">Tests</button>
                <button id="console-btn" class="tablinks" onclick="openTab(event, 'console')">Console</button>
            </div>
            <!-- Tab content -->
            <!-- Description content -->
            <div id="desc" class="md-body tabcontent">
                {{ description }}
            </div>
            <!-- Tests content -->
            <div id="tests" class="tests tabcontent">
                <p>Score: <span id="score-tests" class="color-green"></span> </p><br>
                {% for key, value in test_cases.items %}
                    <button class="accordion">Test {{ key }} </button>
                    <div class="panel">
                        <p><span style="color: #538EFF">Input: </span> <span> {{ value.input }} </span> </p>
                        <p><span style="color: #538EFF">Expected: </span> <span> {{ value.expected }} </span> </p>
                        <p><span style="color: #538EFF">Result: </span> <span id="result-{{ key }}" style="color: yellow"></span> </p>
                    </div>
                {% endfor %}
            </div>
            <!-- Console content -->
            <div id="console" class="tests tabcontent error">
                <p id="results">Result: </p>
            </div>
        </div>
        <div class="container-editor col s8">
            <div id="editor-content" class="">
                <textarea id="editor">{{ func_def }}</textarea>
                <script>
                    let editor = CodeMirror.fromTextArea(document.getElementById('editor'), {
                        lineNumbers: true,
                        mode: "python",
                        theme: "paraiso-dark"
                    });
                    editor.setSize("100%", "93%")
                </script>
            </div>
        </div>

    </div>
    <div class="footer">
        <div class="grouper">
            <button onclick="runTests()" class="sample-button">RUN SAMPLE CODE</button>
            <button id="submit-results-btn" onclick="sendResults()" class="submit-button">SUBMIT CODE</button>
        </div>
    </div>

    <!-- The Modal -->
    <div id="results-modal" class="modal">
      <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Score: <span id="score" class="color-green"></span> </p><br>
            <p id="fail-message" class="color-red">Almost! Keep trying!</p>
            <div id="success-message">
                <p class="color-green">Great job! Go on to the next one!</p>
                <a class="submit-button" href="/challenge?id={{ challenge_id|add:1 }}">Next</a>
            </div>
        </div>
    </div>
</body>

<script>
    function makePost(isReal) {
        $.ajax({
            url: '/challenge',
            type: 'POST',
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}",
                input_code: editor.getValue(),
                challenge_id: {{ challenge_id }},
                is_real: isReal
            },
            dataType: 'json',
            success: function(response) {
                if (response.error != null) {
                    $("#results").text(response.error);
                    document.getElementById("console-btn").click();
                    return;
                }
                if (response.is_real) {
                    $("#score").text(response.score.text);
                    switchTextsInModal(response.score.has_passed);
                    document.getElementById("results-modal").style.display = "block";
                } else {
                    $("#score-tests").text(response.score.text);
                    document.getElementById("tests-btn").click();
                    for (let i = 0; i < response.test_results.length; i++) {
                        $("#result-" + parseInt(i+1)).text(response.test_results[i]);
                    }
                }

            },
            error: function (request, status, error) {
                console.log('ERROR-AJAX: ' + request.responseText)
                $("#results").text("Sorry, try again later :(");
            }
        });

    }

    document.getElementById("desc-btn").click();
    accordion();
    modalPopup();


</script>

</html>

ForkyCodeApp/templates/Forum/createEntry.html
<div class="container">
    <div class="row">
        <div class="col s12 m8">
            <div>
                <a href="#!" role="button" class="btn"
                   data-loading-text="Loading..." data-original-title="" title=""
                    onclick="changeActiveDiv('forum-content')">
                    <i class="material-icons left">navigate_before</i>Back</a>
            </div>
            <br>
            <div class="card-head">
                Describe your topic
            </div>
            <form method="post" action="/createEntry" id="create-entry-form">
                {% csrf_token %}
                <div class="card-panel">
                    <div class="row">
                        <div class="col s12">
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">textsms</i>
                                    <input type="text" id="title-input" name="title" class="autocomplete" aria-required="true" required>
                                    <label for="title-input">Title</label>
                                </div>
                            </div>
                        </div>
                        <div class="col s12">
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">assignment</i>
                                    <textarea id="desc-input" name="desc" class="materialize-textarea" aria-required="true" required></textarea>
                                    <label for="desc-input">Description</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="right">
                    <button type='submit' name='btn_crete_entry'
                            class='btn waves-effect'>Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

ForkyCodeApp/templates/Forum/entry.html
<div class="container">
    <div class="row">
        <div class="col s12 m10 offset-m1">
            <div>
                <a href="#!" role="button" class="btn"
                   data-loading-text="Loading..." data-original-title="" title=""
                    onclick="changeActiveDiv('forum-content')">
                    <i class="material-icons left">navigate_before</i>Back</a>
            </div>
            <br>
            <div class="card-head">
                Topic
            </div>
            <div id="entry_info" class="white">

            </div>
            <br>
            <p>Comments</p><hr>
            <div id="comments_list" class="white">

            </div>
            <hr>

            <div class="post">
                <form action="{% url 'ForkyCodeApp:CreateComment' %}" id="comment_form" class="form" method="post">
                    {% csrf_token %}
                    <div class="topwrap">
                        <div class="posttext left">
                            <div class="textwraper">
                                <div class="postreply">Post a Comment</div>
                                <textarea name="reply" id="reply" placeholder="Type your comment here"></textarea>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="postinfobot">
                        <div class="right postreply">
                            <div class="pull-left"><button type="submit" class="btn btn-primary">Post</button></div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ForkyCodeApp/templates/Forum/forum.html
<div class="container forum">
    <div>
        <div>
            <a href="#!" role="button" class="btn btn-default btn-load"
               data-loading-text="Loading..." data-original-title="" title=""
                onclick="changeActiveDiv('forum-entry-creation-content')">
                <i class="material-icons left">add</i>New Topic</a>
        </div>
        <br>
        <div class="card-head">
            Topics
        </div>
        <div class="card-content white">
            <table class="highlight">
                <thead>
                    <tr>
			        <th class="tableTitle" style="display: table-cell;">Title</th>
                    <th class="tableTitle hide-on-small-only" >Statistics</th>
                    <th class="tableTitle hide-on-small-only" >Last post</th>
                </tr>
                </thead>
                <tbody id="list_forum">

                </tbody>
            </table>
        </div>
        <div id="pagination"></div>
    </div>
</div>

ForkyCodeApp/templates/Landing/landing.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">

  <title>ForkyCode</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/landing.css'%}" rel="stylesheet">

  <!-- Custom styles for this template -->

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/landing.js' %}"></script>
</head>

<body>

    <ul id="slide-out" class="sidenav">
        <li>
            <a href="/" class="brand-logo blue brand-logo-side">ForkyCode</a>
            <div class="user-view">
                <div class="background blue"></div>
            </div>
        </li>
        <li><a class="dropdown-trigger" href="{% url 'ForkyCodeApp:Signup' %}" data-target="dropdown">
            <i class="material-icons">edit</i> Sign Up</a></li>
        <li><a class="dropdown-trigger" href="{% url 'ForkyCodeApp:Login' %}" data-target="dropdown">
            <i class="material-icons">fingerprint</i> Login</a></li>
    </ul>

  <!-- Navigation -->
  <div id="main-nav" class="navbar-fixed">
        <nav>
            <div class="nav-wrapper blue lighten-1">
                <a href="#" class="sidenav-trigger left" data-target="slide-out">
                    <i class="material-icons">menu</i>
                </a>
                <a href="/" class="left brand-logo brand-logo-m hide-on-small-only">ForkyCode</a>
                <a href="/" class="brand-logo brand-logo-s center hide-on-med-and-up">ForkyCode</a>

                <ul class="right hide-on-med-and-down">
                    <li>
                        <a class="dropdown-trigger" href="{% url 'ForkyCodeApp:Signup' %}" data-target="dropdown">
                            <i class="material-icons right">edit</i>
                            Sign Up
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-trigger" href="{% url 'ForkyCodeApp:Login' %}" data-target="dropdown">
                            <i class="material-icons right">fingerprint</i>
                            Login
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

  <div class="container">
        <div class="row vertical-content center">
            <div class="col s12 offset-m2 m8 white-text">
                <h1 class="home-heading">Real-World Coding Environment</h1>
                <p class="home-subtitle mx-auto mt-3">Get your coding skills on edge, practice for technical interviews and build your developer resume. </p>
                <div class="home-button mt-4">
                    <a href="{% url 'ForkyCodeApp:Signup' %}" class="btn-large mt-3">Free Signup</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

ForkyCodeApp/templates/Leaderbords/leaderboards.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Leaderboards</title>
    <link rel="stylesheet" href="{% static 'css/leaderbords.css' %}">
</head>
<body>
<div class="container">
    <ul class="collection with-header" id="list_leaderbords">


    </ul>
</div>
</body>
</html>

ForkyCodeApp/templates/Login/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.ico' %}"/>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    <style>
        @import url('https://fonts.googleapis.com/css?family=Mansalva&display=swap');
        @import url('https://fonts.googleapis.com/css?family=Montserrat&display=swap');
        .input-field input[type=date]:focus + label,
        .input-field input[type=text]:focus + label,
        .input-field input[type=email]:focus + label,
        .input-field input[type=password]:focus + label {
            color: #2196F3 !important;
        }

        .input-field input[type=date]:focus,
        .input-field input[type=text]:focus,
        .input-field input[type=email]:focus,
        .input-field input[type=password]:focus {
            border-bottom: 2px solid #2196F3 !important;
            box-shadow: none;
        }

        body{
            background: lightblue;
            background-size: 100% auto;
            font-family: 'Montserrat', sans-serif !important;
        }

        nav {
            background-color: #2196F3 !important;
        }
        @media (min-width: 993px) {
            .brand-logo {
                padding-left: 2% !important;
            }
        }

        a.brand-logo {
            font-family: 'Mansalva', cursive;
        }

    </style>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo">ForkyCode</a>
        </div>
    </nav>
    <main>
        <div class="section"></div>
        <div class="row hide-on-large-only">
            <div class="col s10 offset-s1 center">
                <h4>Yay! You're back!</h4>
                <p>Login into your account and complete challenges and assessments in a real-world coding environment.</p>
            </div>
        </div>
        <br style="display: none" class="show-on-large">
        <div class="row">
            <div class="col s5 l5 xl5 offset-s1 offset-l1 offset-xl1 hide-on-med-and-down">
                <h4>Yay! You're back!</h4>
                <p>Login into your account and complete challenges and assessments in a real-world coding environment.</p>
                <br>
                <img src="{% static 'media/login.png' %}" alt="" width="100%">
            </div>
            <div class="col s10 m6 l4 offset-s1 offset-m3 offset-l1 xl4 offset-xl1 z-depth-1 grey lighten-4 center" style="max-width:450px;display: inline-block; padding: 32px 48px 0px 48px; box-shadow: 0px 0px 10px 1px #cccccc;">
                <form class="col s12" method="post">
                        {% csrf_token %}
                        <div class='row'>
                            {% if error %}
                                <script>
                                    M.toast({html: '{{ error }}', classes: 'red lighten-1'})
                                </script>
                            {% endif %}
                            <div class='input-field col s12'>
                                <input class='validate' type='email' name='email' id='email' required="" aria-required="true"/>
                                <label for='email'>Email</label>
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='password' name='password' id='password' required="" aria-required="true"/>
                                <label for='password'>Password</label>
                            </div>
                            <label style='float: right;'>
                                <a class='blue-text' href='#!'><b>Forgot Password?</b></a>
                            </label>
                        </div>
                        <br />
                        <div class="center">
                            <div class='row'>
                                <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect blue'>Login</button>
                            </div>
                        </div>
                        <div class='row center'>
                            <label>
                                No account? <a href="/signup">Sign up here!</a>
                            </label>
                        </div>
                    </form>
            </div>
        </div>
    </main>
</body>

</html>

ForkyCodeApp/templates/Navbar/editor-navbar.html
<!-- Dropdown DESKTOP -->
<ul id="dropdown" class="dropdown-content white">
    <li><a href="#!" onclick="submitLogout()">Sign Out</a></li>
</ul>

<!-- Main NAV -->
<div id="main-nav" class="navbar-fixed" style="height: 50px;">
    <nav style="height: 40px; line-height: 40px!important;">
        <div class="nav-wrapper blue lighten-1">
            <a href="/" class="left">
                <i class="material-icons left" style="height: 40px;line-height: 40px;margin-left: 10px;">
                    arrow_back
                </i>
                Back
            </a>
            <a href="#" class="func-name">{{ func_name }}</a>
            <ul class="right hide-on-med-and-down">
                <li>
                    <a class="dropdown-trigger" href="#!" data-target="dropdown">
                        <i class="material-icons right" style="height: 40px;line-height: 40px;margin-left: 10px;">arrow_drop_down</i>
                        Settings
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

ForkyCodeApp/templates/Profile/profile.html
<div class="container">
    <div class="row">
        <div class="col card s12 m4 white" id="profile_info">


        </div>
        <div class="col s12 m7 offset-m1" id="profile_extra">

        </div>
    </div>
</div>